# Generated by Django 3.1 on 2024-04-10 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.IntegerField(default=0)),
                ('result', models.IntegerField(default=0)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('priority', models.IntegerField(default=0)),
                ('process_info', models.CharField(blank=True, max_length=255, null=True)),
                ('process_num', models.IntegerField(default=-1)),
                ('find', models.IntegerField(default=1)),
                ('image_oss_url', models.CharField(default='', max_length=200)),
                ('feature1', models.FloatField(default=0)),
                ('feature2', models.FloatField(default=0)),
                ('task_type', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
            },
        ),
    ]
