# Generated by Django 3.1 on 2024-04-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_remove_schedule_ga_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='result',
            field=models.TextField(default=''),
        ),
    ]
