# Generated by Django 3.1 on 2024-04-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20240419_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='feature1',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='feature2',
        ),
        migrations.AddField(
            model_name='schedule',
            name='p1_oss_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='schedule',
            name='p2_oss_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='schedule',
            name='p3_oss_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
