# Generated by Django 3.1 on 2024-04-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_remove_schedule_find'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='process1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='schedule',
            name='process2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='schedule',
            name='process3',
            field=models.FloatField(default=0),
        ),
    ]
