# Generated by Django 3.1 on 2024-04-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='工号')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('kind', models.IntegerField(default=2, verbose_name='权限')),
                ('tel_number', models.CharField(max_length=12, verbose_name='电话号码')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱号码')),
                ('user_bool', models.BooleanField(default='True', verbose_name='存在')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
    ]
